#pragma once

#include <cstdint>

#define SYSTEM_TICK_PERIOD_MS 1U
#define TOUCH_SCAN_PERIOD_MS 10U
#define STORAGE_DETECT_PERIOD_MS 100U
#define MAIN_LOOP_DELAY_MS 1U
#define SYSTEM_EVENTS_PER_UPDATE 8U

static_assert(TOUCH_SCAN_PERIOD_MS % SYSTEM_TICK_PERIOD_MS == 0U);
static_assert(STORAGE_DETECT_PERIOD_MS % SYSTEM_TICK_PERIOD_MS == 0U);
static_assert(SYSTEM_EVENTS_PER_UPDATE > 0U);
