#pragma once

#define PAPER_MONO_DISPLAY_ROTATION 0U
#define PAPER_MONO_DISPLAY_WIDTH 480U
#define PAPER_MONO_DISPLAY_HEIGHT 800U

// Native SSD1677 framebuffer geometry used by the manufacturer OTP example.
#define PAPER_MONO_EPD_NATIVE_WIDTH 800U
#define PAPER_MONO_EPD_NATIVE_HEIGHT 480U
#define PAPER_MONO_EPD_BYTES_PER_ROW (PAPER_MONO_EPD_NATIVE_WIDTH / 8U)
#define PAPER_MONO_EPD_FRAME_SIZE \
    (PAPER_MONO_EPD_BYTES_PER_ROW * PAPER_MONO_EPD_NATIVE_HEIGHT)
#define PAPER_MONO_EPD_CANVAS_ROTATION 5U

// PaperMono EPD SPI2 pin map.
#define PAPER_MONO_EPD_GPIO_MOSI 14
#define PAPER_MONO_EPD_GPIO_SCLK 15
#define PAPER_MONO_EPD_GPIO_CS 16
#define PAPER_MONO_EPD_GPIO_DC 17
#define PAPER_MONO_EPD_GPIO_BUSY 18
#define PAPER_MONO_EPD_SPI_CLOCK_HZ (20 * 1000 * 1000)
#define PAPER_MONO_EPD_SPI_CHUNK_SIZE 4092U
#define PAPER_MONO_EPD_BUSY_TIMEOUT_MS 15000U

// M5IOE1 uses zero-based pin indexes.
#define PAPER_MONO_EPD_IOE_ENABLE 2U
#define PAPER_MONO_EPD_IOE_RESET 4U
#define PAPER_MONO_EPD_IOE_TIMEOUT_MS 100U
#define PAPER_MONO_EPD_RESET_LOW_MS 10U
#define PAPER_MONO_EPD_RESET_HIGH_MS 10U
#define PAPER_MONO_EPD_DEEP_SLEEP_DELAY_MS 100U

// Run one full monochrome OTP cleanup after this many physical partial updates.
#define PAPER_MONO_EPD_PARTIAL_REFRESH_LIMIT 10U
