idf_component_register(
    SRCS
        "battery/battery_service.cpp"
        "front_light/front_light_service.cpp"
        "input/input_service.cpp"
        "rtc/rtc_service.cpp"
        "storage/storage_service.cpp"
        "storage/storage_file_reader.cpp"
        "book/book_service.cpp"
        "book/book_format.cpp"
        "book/book_index_engine.cpp"
        "book/epub_archive.cpp"
        "book/epub_cache_engine.cpp"
        "book/epub_format.cpp"
        "system_tick/system_tick_service.cpp"
    INCLUDE_DIRS "include/services"
    REQUIRES
        core
        m5_hal
        esp_driver_gptimer
    PRIV_REQUIRES
        json
        mbedtls
        esp_rom
)
